# Generated by Django 2.2.7 on 2021-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matric_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
